# Общие настройки Gradle. Настройки из Android Studio могут переопределять их.
# Выделяем процессу Gradle до 2 ГБ памяти и используем UTF-8.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Параллельную сборку можно включить, если модули не зависят друг от друга.
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
# Кеш конфигурации ускоряет повторные сборки, когда настройки проекта не менялись.
org.gradle.configuration-cache=true
# Используем стандартный стиль форматирования Kotlin.
kotlin.code.style=official
